"""
@author: David Herron
"""

'''
This module specifies an implementation for a concrete visitor class for 
evaluating the truth value of propositional logic (CNF) expressions 
represented as parse trees of the ANTLR v4 grammar CNF.g4
 
The visitor walks the parse tree for a CNF expression in depth-first, 
post-order traversal fashion. Post-order means a node's children are
visited first, before the node performs and concludes its own business,
if any. Depth-first, post-order traversals are guaranteed to be 
topological, meaning that when determining a node's truth value, all
relevant dependencies will have been satisfied (aka children processed).

A visitor is instantiated for a given truth-value assignment, which is
subsequently used to evaluate the truth value of any CNF expressions
requiring processing.
'''

from antlr4 import *
from .CNFParser import CNFParser
from .CNFVisitor import CNFVisitor


class CNFVisitorA(CNFVisitor):

    '''
    A custom visitor for visiting parse trees of CNF expressions,
    generated by the PLRE, in order to evaluate their truth value,
    given a truth-value assignment.
    '''

    def __init__(self, propSymbolSet:list,
                       truthValueAssignment:list,
                       verbose:bool = False):
        super().__init__()

        # verify there are no duplicate symbols
        propSymbolSet2 = set(propSymbolSet)
        if len(propSymbolSet2) < len(propSymbolSet):
            raise ValueError('propSymbolSet contains duplicate symbols')
        self.propSymbolSet = propSymbolSet

        # verify the validity of the truthValueAssignment
        if not isinstance(truthValueAssignment, list): 
            raise ValueError('a truth-value assignment (list) is required')
        if len(truthValueAssignment) > len(propSymbolSet):
            raise ValueError('a truth-value assignment cannot be larger than propSymbolSet')
        # (note: it is valid for a tVA to be empty, i.e. for no symbol to be True)
        for symbol in truthValueAssignment:
            if not symbol in propSymbolSet:
                raise ValueError(f'symbol in truth-value assignment not in propSymbolSet: {symbol}')
        self.truthValueAssignment = truthValueAssignment    

        # initialise container for tracking which symbols are referenced 
        # in CNF expressions and which not
        self.propSymbolUsage = [False] * len(propSymbolSet)

        self.verbose = verbose


    def visitCnf(self, ctx:CNFParser.CnfContext):

        # Calculate the number of clauses in the CNF expression
        # as a function of the number of its children.
        # getChildCount(): 2,     4,       6,         8, ...
        # nr of clauses  : 1,     2,       3,         4, ...
        # child indexes  : 0, [0,2], [0,2,4], [0,2,4,6], ...
        nr_clauses = int(ctx.getChildCount() / 2)

        # Initialise the truth value for the CNF expression being
        # evaluated. Using 'True' here is the correct initial value 
        # because it has a null effect on the ultimate cumulative 
        # truth value of the conjunction of CNF clauses in the overall
        # CNF expression.
        truthValue_cum = True     

        # Iterate over the CNF clauses of the CNF expression.
        # We step over the conjunction (AND) operators, but we perform
        # a logical AND operation anyway, for each successive clause,
        # because we know the logical AND operators are there. We don't 
        # need to retrieve them.  We assume the syntax of the CNF
        # expression being processed is valid, because otherwise syntax
        # errors would have been detected and reported during parsing.
        for clauseIdx in range(nr_clauses):
            childIdx = int(clauseIdx * 2)
            truthValue = self.visit(ctx.getChild(childIdx))
            truthValue_cum = truthValue_cum and truthValue

        return truthValue_cum
    

    def visitClause(self, ctx:CNFParser.ClauseContext):
 
        # A clause may be surrounded by LPAREN '(' and RPAREN ')', but a single
        # literal is also feasible. So we have to handle both cases.
        # If nr_children is 1 (ie < 3), we no parentheses (single literal only).
        # If nr_children is >= 3, we have parentheses (and potentially a single
        # literal only, but potentially a disjunction of multiple literals)
        no_parentheses = ctx.getChildCount() < 3
      
        # we can ignore (side-step) the parentheses because they don't contribute
        # to resolving the disjunction of truth values 

        # calculate the number of literals in the clause as a function of
        # the number of children;
        # getChildCount(): 1, 3,     5,       7,         9, ...
        # nr of literals : 1, 1,     2,       3,         4, ...
        # child indexes  : 0, 1, [1,3], [1,3,5], [1,3,5,7], ...
        if ctx.getChildCount() == 1:
            nr_literals = 1
        else:
            nr_literals = ctx.getChildCount() // 2

        if no_parentheses:   # L
            # visit the first (only) literal and return its truth value
            truthValue = self.visit(ctx.getChild(0))
            if self.verbose:
                print(f'visitClause clause truthValue: {truthValue}')
            return truthValue

        truthValue = self.visit(ctx.getChild(1))
        if ctx.getChildCount() == 3: # (L)
            if self.verbose:
                print(f'visitClause clause truthValue: {truthValue}')
            return truthValue

        # Skip over the '|' (OR) disjunction operators and process
        # only the literals. Assume the disjunctions are there, and 
        # process them accordingly, but without bothering to actually
        # retrieve them.

        # literal Idx : 0, 1, 2, 3, 4, ...    
        # child Idx   : 1, 3, 5, 7, 9, ...    (2 x lI) + 1

        truthValue_cum = truthValue
        for literalIdx in range(1, nr_literals):
            childIdx = (literalIdx * 2) + 1
            truthValue = self.visit(ctx.getChild(childIdx))
            truthValue_cum = truthValue_cum or truthValue

        if self.verbose:
            print(f'visitClause clause truthValue: {truthValue_cum}')

        return truthValue_cum



    def visitLiteral(self, ctx:CNFParser.LiteralContext):
  
        if ctx.getChildCount() == 2:  # NOT atom
            op = ctx.getChild(0).getText()
            if op in ['~', '!', 'NOT']:
                return not self.visit(ctx.getChild(1))
            else:
                raise ValueError('negation operator not recognised')
        
        if ctx.getChildCount() == 1:  # atom
            return self.visit(ctx.getChild(0))
        
        # we should never get this far, so the question of what to
        # return if we do get this far is somewhat moot --- but 
        # what we're returning is NOT expected to work; returning 
        # text will foul up the Boolean logic being performed

        return ctx.getText()
    

    def visitAtom(self, ctx:CNFParser.AtomContext):
        # an atom node is a leaf node of the parse tree, whose text 
        # is a propositional symbol within a CNF expression
        propSymbol = ctx.getText()

        # verify that the propositional symbol encountered in the CNF 
        # expression is a member of the set of propositional symbols
        # specified for this visitor
        if not propSymbol in self.propSymbolSet:
             raise ValueError(f'symbol in CNF expression not recognised: {propSymbol}')
        
        # record which propositional symbols have been used in one or more 
        # CNF expressions, so we can identify and report which symbols have not
        idx = self.propSymbolSet.index(propSymbol)
        self.propSymbolUsage[idx] = True

        # assign specified truth value to propositional symbol
        if propSymbol in self.truthValueAssignment:
            truthValue = True
        else:
            truthValue = False
        
        return truthValue  





